# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

platform :ios do
    desc "Try to build project"
    lane :try_build do
      scan(
        clean: true,
        devices: ["iPhone 12", "iPhone 14 Pro", "iPhone 15", "iPhone 15 Pro"],
        skip_build: true,
        build_for_testing: true 
      )
    end
end
